---
title: "Visualization Critique"
author: "Muhammad Imdad Ullah"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Visualization Link

Please provide a link to your visualization critique.

<https://github.com/itfeature/tempwork/blob/main/visualization%20critiques%202.rmd>[https://github.com/itfeature/tempwork/blob/main/visualization%20critiques%202.rmd]

## Weakness

The small test and reliance on color may hinder colorblined users. For mobile users, the interactive elements may be harder to navigate on phones. It compares to 20th century average, but some users might misinterpret normal. The raw data source link is not available. Data is for Global users, but US users can input "hometowns" (it shows a limited scope). 


## Strength

New York Times (2024): "How Much Hotter is Your Hometown Than When you Were Born?"
The visualization used was line chart with geographic input that shows temperature trends over time and it is interactive as use inputs increases the engagement and relevance. The annotations is used that explains data sources (NOAA) and uncertainties with red color gradient for temperature intuitively signals "danger".
